apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: eks-demo
  region: us-west-2

#kubernetesNetworkConfig:
#  ipFamily: IPv6

## Add-ons are required for IPv6. Why? Unknown. Maybe irrelevant in the future.
#addons:
#  - name: vpc-cni
#    version: latest
#  - name: coredns
#    version: latest
#  - name: kube-proxy
#    version: latest

iam:
  # Er wordt een OIDC aangemaakt. AWS is de resource, het cluster is de resource owner.
  withOIDC: true
  serviceAccounts:
    # Alternatieve methoden om een policy te beschrijven,
    # zie https://medium.com/@marcenschede/eks-complete-with-eksctl-sprint-2-6ec2ab518e76
    - metadata:
        name: aws-load-balancer-controller
        namespace: kube-system
      wellKnownPolicies:
        awsLoadBalancerController: true
    - metadata:
        name: bitnami-external-dns-controller
        namespace: bitnami-external-dns
      wellKnownPolicies:
        externalDNS: true
    - metadata:
        name: cluster-autoscaler
        namespace: kube-system
      # inline policy can be defined along with `attachPolicyARNs`
      attachPolicy:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - "autoscaling:DescribeAutoScalingGroups"
              - "autoscaling:DescribeAutoScalingInstances"
              - "autoscaling:DescribeLaunchConfigurations"
              - "autoscaling:DescribeScalingActivities"
              - "autoscaling:DescribeTags"
              - "ec2:DescribeInstanceTypes"
              - "ec2:DescribeLaunchTemplateVersions"
            Resource: '*'
          - Effect: Allow
            Action:
              - "autoscaling:SetDesiredCapacity"
              - "autoscaling:TerminateInstanceInAutoScalingGroup"
              - "ec2:DescribeImages"
              - "ec2:DescribeInstanceTypes"
              - "eks:DescribeNodegroup"
            Resource: '*'
      # refering to a policy defined in IAM
#      attachPolicyARNs:
#        - "arn:aws:iam::228991124303:policy/EKSClusterAutoscalerPolicy"

managedNodeGroups:
  - name: prod
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 2
    maxSize: 6
    spot: true
    iam:
      withAddonPolicies:
        cloudWatch: true
        autoScaler: true
    tags:
      # needed for autoscaler
      k8s.io/cluster-autoscaler/eks-demo: owned
      k8s.io/cluster-autoscaler/enabled: "true"

gitops:
  # All application that needs to be spinned up are in https://github.com/enschede/eks-demo-infra
  flux:
    gitProvider: github
    flags:
      owner: "enschede"
      repository: "eks-demo-infra"
      private: "true"
      branch: "main"
      namespace: "flux-system"
      path: "app-cluster"
