---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: crossplane-infra
  namespace: flux-system
spec:
  interval: 1m
  ref:
    branch: main
  url: https://github.com/enschede/crossplane-infra.git
  secretRef:
    name: github-credentials

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: crossplane-infra-phase1
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  interval: 1m
  path: "./deployment/phase1"
  prune: true
  sourceRef:
    kind: GitRepository
    name: crossplane-infra

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: crossplane-infra-phase2
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  dependsOn:
    - name: crossplane-infra-phase1
  interval: 1m
  path: "./deployment/phase2"
  prune: true
  sourceRef:
    kind: GitRepository
    name: crossplane-infra

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: crossplane-infra-phase3
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  dependsOn:
    - name: crossplane-infra-phase2
  interval: 1m
  path: "./deployment/phase3"
  prune: true
  sourceRef:
    kind: GitRepository
    name: crossplane-infra
