---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: networktools
  namespace: flux-system
spec:
  interval: 1m
  ref:
    branch: main
  url: https://github.com/enschede/eks-demo-networktools.git
  secretRef:
    name: github-credentials

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: networktools
  namespace: flux-system
spec:
  interval: 1m
  path: "./deployment"
  prune: true
  sourceRef:
    kind: GitRepository
    name: networktools
