---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: eks-demo-app
  namespace: flux-system
spec:
  interval: 1m
  ref:
    branch: sprint4
  url: https://github.com/enschede/eks-demo-app.git

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: eks-demo-app
  namespace: flux-system
spec:
  interval: 1m
  path: "./deployment"
  prune: true
  sourceRef:
    kind: GitRepository
    name: eks-demo-app
  postBuild:
    substituteFrom:
      - kind: Secret
        name: aws
