---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: eks-demo-app
  namespace: flux-system
spec:
  interval: 1m
  ref:
    branch: sprint5
  url: https://github.com/enschede/eks-demo-app.git
  secretRef:
    name: github-credentials

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: eks-demo-app-crossplane
  namespace: flux-system
spec:
  interval: 1m
  path: "./crossplane"
  prune: true
  sourceRef:
    kind: GitRepository
    name: eks-demo-app
  dependsOn:
    - name: crossplane-infra-phase3

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: eks-demo-app-db
  namespace: flux-system
spec:
  interval: 1m
  path: "./db"
  prune: true
  sourceRef:
    kind: GitRepository
    name: eks-demo-app
  dependsOn:
    - name: eks-demo-app-crossplane

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: eks-demo-app
  namespace: flux-system
spec:
  interval: 1m
  path: "./deployment"
  prune: true
  sourceRef:
    kind: GitRepository
    name: eks-demo-app
  postBuild:
    substituteFrom:
      - kind: Secret
        name: aws
  dependsOn:
    - name: eks-demo-app-db
    - name: load-balancer-controller
    - name: external-dns
